config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  root :to => "pages#home"

  match '/home',    :to => 'pages#home',       via: 'get'
  match '/about',   :to => 'pages#about',      via: 'get'
  match '/faq',     :to => 'pages#faq',        via: 'get'
  match '/help',    :to => 'pages#help',       via: 'get'
  match '/signup',  :to => 'users#new',        via: 'get'
  match '/signin',  :to => 'sessions#new',     via: 'get'
  match '/signout', :to => 'sessions#destroy', via: 'get'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                   :integer          not null, primary key
#  name                 :string(255)
#  email                :string(255)
#  created_at           :datetime
#  updated_at           :datetime
#  encrypted_passwomord :string(255)
#
class User < ActiveRecord::Base

  attr_accessor        :password

  validates :name,     :presence    => true, 
                       :length      => {:maximum => 50 }

  Valid_email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :email,    :presence   => true, 
                       :format     => { :with => Valid_email_regex },
                       :uniqueness => {:case_sensitive => false}

  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..40 }

  before_save :encrypt_password

  def has_password?(submitted_password)
    self.encrypted_password == encrypt(submitted_password)
  end
  
  class << self

    def authenticate(email, submitted_password)
      user = find_by_email(email)
      return nil  if user.nil?
      return user if user.has_password?(submitted_password)
    end
  end

  private 

    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
    
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end                     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@title = 'Home'
  end

  def contact
  	@title = 'Contact'
  end

  def about
  	@title = 'About'
  end

  def help
  	@title = 'Help'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
 	@title = "Sign in"
 	render :new
  end

  def create
  	user = User.authenticate(params[:sessions][:email],
  		                     params[:sessions][:password])
  	if user.nil?
      flash.now[:error] = "Invalid email/password combination."
      @title = "Sign in"
  	  render :new
  	else
  		#handle successful 
  	end
  end

  def destroy
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  	@user = User.find(params[:id])
  	@title = @user.name
  end

  def new
    @user = User.new
  	@title = "Sign up"
  end

  def create
     #raise params[:user].inspect

     @user = User.new(user_params)
     if @user.save
       redirect_to @user, :flash => { :success => "Welcome to the Sample App!" }
     else
       @title = "Sign up"
       render 'new'
     end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns a title on a per-page basis.
  def title
    base_title = "iAnalysis polling and surveying community"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
  def logo
  	image_tag("logo2.png", :alt => "iAnalysis", :class => "round")
  end
  
  def survey2
    image_tag("survey3.png", :alt => "iAnalysis", :class => "round")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user, options = { :size => 50 })
      gravatar_image_tag(user.email.downcase, :alt => user.name,
      	                                      :class => 'gravatar',
      	                                      :gravatar => options)
	end
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
  	<ul>
  		<li><%= link_to "About", about_path %></li>
  		<li><%= link_to "FAQ", faq_path %></li>
  		<li><%= link_to "Register", signup_path %></li>
  	</ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>
  <nav class="round">
  	<ul>
      <li><FONT SIZE=3 COLOR="NAVY" FACE="VERDANA">
		  <%= link_to "Home",    root_path %></li>
      <li><%= link_to "Help",    help_path %></li>
      <li><%= link_to "Sign in", signin_path %></li>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
  	<div class="container">
      <%= render 'layouts/header' %>
  	  <section class="round">
        <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
        <% end %>
  	  	<%=  yield %>
  	  </section>
  	  <%= render 'layouts/footer' %>

    </div>
  </body>
</html> 

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>
  This is the about page for the iAnalysis polling and surveying community.
</p>

app/views/pages/faq.html.erb
<h1>FAQ</h1>
<p>
  This is the Frequently Asked Questions page for the iAnalysis polling and surveying community.
</p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>
   This is the Help page for the iAnalysis polling and surveying community.
</p>

app/views/pages/home.html.erb
<h1></h1>
<p>
  We want to know what you think!                            
  <br>                   ...and are willing to pay for it!
</p>

<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error") %>
      prohibited this user from being saved:
    <h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>
  <div class="field">   
    <%= f.label :name %><br />
    <%= f.text_field :name %><br />

    <%= f.label :email %><br />
    <%= f.text_field :email %><br />

    <%= f.label :password %><br />
    <%= f.password_field :password %><br />

    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %><br />

    <%= f.submit "Create my account", class: "btn btn-primary" %><br />
  </div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile Information">
  <tr>
  	<td class="main">
      <h1>
	    <%= gravatar_for @user %>
	    <%= @user.name %>
      </h1>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.name %><br />
      <strong>URL</strong> <%= link_to user_path(@user), user_path(@user) %>
    </td>
  </tr>
</table>